favorite-color: ENC[AES256_GCM,data:xCT431w=,iv:N8wia4++bB3QPeVRMX/kyzlJnPn7oteEJ7qPZUWbM2Y=,tag:70xV+Tsq/ATOhrrc1TQhgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwzdtznh6mp4u9ymc4lx9343np52gwrjet9vp0wtqw0gkcdkm92qvms9rm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdEtCNHJKMWtUbjN3WkNO
            QVdBeWF1bWVqa1JxZHdLQlEvemR4YkJhRzNRCkRhWXZvaUhFSXljSmNqMW84L3N1
            MSs2d2hqUTRNVHRFWGUrWVpRODBtUk0KLS0tIEJvTVhaOFpudXNkYUZ4QkhWWm9x
            WjZ5Mi9xMTd3Sm5FUHQ4dTBVSWVHSTQKFWVNLsF1KoY7l0FM95XY0N4cl+k7kjjV
            v8fQz3AfZWnIOU71Uo0ef2dutO7RP+NqxeuV7+UzKJcFhEfBnpOPtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T11:27:31Z"
    mac: ENC[AES256_GCM,data:Zax9rMfapSMi4a5SlHOAcMu25hmbJABeQsZkE+7JgHgfkEbtzQkkZSLGkk/ATEizM+d81tx6T/nCy1n1zoe/4QhnneXstsiQVP2WNJfxfRNZCi1EIEYW55OzGNn9HkPiqx7WZEP3koPdNgi3W4HpH6UgZ94P3K301v8hQlHD/IQ=,iv:twUkyFtzdHKOYtk6WW4Ks7lIiWzRfKcArBJ962T3Fds=,tag:njaOqXKBR0wACAXjepgozQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
