set -g status off
set-option -g history-limit 5000
set -g renumber-windows on # Prevent gaps in ids
set -g xterm-keys on

set -g main-pane-width 50%
set-hook -g pane-exited select-layout

# Nvim-required options
set-option -sg escape-time 10
set-option -g default-terminal "screen-256color"
set-option -sa terminal-features ',xterm-kitty:RGB'

unbind [
bind -n M-v copy-mode \; send-keys -X halfpage-up \; send-keys -X start-of-line
unbind -T copy-mode-vi $
bind -T copy-mode-vi L send-keys -X end-of-line
unbind -T copy-mode-vi 0
bind -T copy-mode-vi H send-keys -X start-of-line
unbind -T copy-mode-vi C-d
bind -T copy-mode-vi J send-keys -X halfpage-down
unbind -T copy-mode-vi C-u
bind -T copy-mode-vi K send-keys -X halfpage-up
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi Space send-keys -X rectangle-toggle
bind -T copy-mode-vi C-c send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel

unbind -T copy-mode MouseDragEnd1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane

# Use the current path during splitting
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

unbind C-b
set -g prefix M-a
bind M-a send-prefix

bind -n M-h select-pane -t :.-
bind -n M-l select-pane -t :.+
bind -n M-j resize-pane -L 3
bind -n M-k resize-pane -R 3
bind -n C-M-j resize-pane -D 3
bind -n C-M-k resize-pane -U 3
bind -n M-H swap-pane -t :.- \; select-pane -t :.-
bind -n M-L swap-pane -t :.+ \; select-pane -t :.+

bind -n M-Enter split-window -h -c "#{pane_current_path}" \; select-layout
bind c kill-pane

# Toggle status bar
bind -n M-b set -g status

# Toggle pane fullscreen zoom
bind -n M-f resize-pane -Z
